[package]
name = "wit"
version = "0.2.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/wit.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"
